name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the appropriate Node.js version for your project

      - name: Install dependencies
        run: |
          cd frontend
          npm install  # Or the appropriate install command for your project

      - name: Build project
        run: |
          cd frontend
          npm run build  # Or the appropriate build command for your project

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build  # Adjust this path to your build output directory
